apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: kserve-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: mlflow-lab:latest
          imagePullPolicy: Never
          args:
            - "--backend-store-uri"
            - "postgresql://mlflow:mlflow123@postgres.kserve-lab.svc.cluster.local:5432/mlflow"
            - "--default-artifact-root"
            - "s3://mlflow/"
          ports:
            - containerPort: 5000
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
